[package]
name = "dead_woman_switch"
version = "0.1.0"
edition = "2021"
authors = ["TudbuT", "JessSystemV"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
